#配置端口和tomcat编码
server:
  port: 9100
spring:
  profiles:
    active: common
  application:
    name: auth
  #配置数据源
  datasource:
    druid:
      username: auth
      password: auth@123
      url: jdbc:mariadb://www.shawsx.com:3306/auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
      driver-class-name: org.mariadb.jdbc.Driver
      initial-size: 10
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      validation-query: SELECT 1
      #配置Druid监控
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid.gz
        login-password: druid.gz
  redis:
    host: www.shawsx.com
    database: 0
    port: 6379
    password: Xiaosx980525*
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: 3000
        max-idle: 20
        min-idle: 5
      cluster:
        refresh:
          period: 20
          adaptive: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
