server:
  port: 9200
spring:
  profiles:
    active: common
  application:
    name: drive
  data:
    mongodb:
      host: www.shawsx.com
      username: test
      password: test
      port: 27017
      database: test
  datasource:
    druid:
      username: drive
      password: drive@123
      url: jdbc:mariadb://www.shawsx.com:3306/drive?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
      driver-class-name: org.mariadb.jdbc.Driver
      initial-size: 10
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      validation-query: SELECT 1
      #配置Druid监控
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid.gz
        login-password: druid.gz
minio:
  endpoint: minio.shawsx.com
  port: 8443
  region: cn-1
  accessKey: spring
  secretKey: spring@123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/

