server:
  port: 9200
spring:
  profiles:
    active: common
  application:
    name: drive
  data:
    mongodb:
      host: www.shawsx.com
      username: test
      password: test
      port: 27017
      database: test
minio:
  endpoint: minio.shawsx.com
  port: 8443
  region: cn-1
  accessKey: spring
  secretKey: spring@123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/

