server:
  port: 9300
spring:
  application:
    name: questionnaire
  datasource:
    druid:
      username: question
      password: question@123
      url: jdbc:mariadb://www.shawsx.com:3306/questionnaire?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
      driver-class-name: org.mariadb.jdbc.Driver
      initial-size: 10
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      validation-query: SELECT 1
      #配置Druid监控
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid.gz
        login-password: druid.gz
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/